% Получение данных, которые создаются в примере rsiot/examples/cmp_tsdb

addpath("../src")

connection = postgresql("postgres", "postgres", ...
    Server = "localhost", ...
    DatabaseName = "db_data", ...
    PortNumber = 5432 ...
    );

now = string_to_datetime('now');
time_start = now - seconds(1000);
time_end = now - seconds(1);

data = fetch_from_tsdb( ...
    connection, ...
    time_start, ...
    time_end, ...
    hst = "hst_test",...
    svc = "svc_test", ...
    cmp = "cmp_inject_periodic",...
    key = "counter" ...
    );

plot(data.time, data.value);