function data = fetch_from_tsdb( ...
    connection, ...
    time_start, ...
    time_end, ...
    options ...
    )

% Получение данных с БД TimescaleDB
%
% Пример
% 
%   connection = postgresql("postgres", "postgres", ...
%     Server = "localhost", ...
%     DatabaseName = "db_data", ...
%     PortNumber = 5432 ...
%     );
% 
%   now = string_to_datetime('now');
%   time_start = now - seconds(1000);
%   time_end = now - seconds(1);
% 
%   data = fetch_from_tsdb( ...
%     connection, ...
%     time_start, ...
%     time_end, ...
%     hst = "hst_test",...
%     svc = "svc_test", ...
%     cmp = "cmp_inject_periodic",...
%     key = "counter" ...
%     );

arguments (Input)
    connection % Ссылка на подключение к PostgreSQL
    time_start datetime
    time_end datetime
    options.hst string
    options.svc string
    options.cmp string
    options.key string
end

arguments (Output)
    data timetable
end

time_start = string(time_start);
time_end = string(time_end);

sql = sprintf("SELECT ""time"", value FROM raw WHERE ""time"" BETWEEN '%s' AND '%s' AND hst = '%s' AND svc = '%s' AND cmp = '%s' AND key = '%s' ORDER BY ""time"" ASC", ...
    time_start, ...
    time_end, ...
    options.hst, ...
    options.svc, ...
    options.cmp, ...
    options.key ...
    );

data = fetch(connection, sql);
data = table2timetable(data);

end
