function data = fetch_from_tsdb( ...
    connection, ...
    time_start, ...
    time_end, ...
    table, ...
    fields ...
)

% Получение данных с БД TimescaleDB
%
% Пример
% 
%   connection = postgresql("postgres", "postgres", ...
%     Server = "localhost", ...
%     DatabaseName = "db_data", ...
%     PortNumber = 5432 ...
%     );
% 
%   time_end = datetime("now", TimeZone="Europe/Minsk");
%   time_start = time_end - seconds(300);
%
%   time_start = string_to_datetime("2025-12-04T09:04:30.000000000+03:00");
%   time_end = time_start + seconds(120);
% 
%   data = fetch_from_tsdb_2( ...
%     connection, ...
%     time_start, ...
%     time_end, ...
%     "prj_ust_panel$hst_pc$svc_backend$cmp_external_process$data",...
%     ["fan_current"] ...
%   );

arguments (Input)
    connection % Ссылка на подключение к PostgreSQL
    time_start datetime
    time_end datetime
    table string
    fields string
end
 
arguments (Output)
    data timetable
end

time_start = string(time_start, 'uuuu-MM-dd''T''HH:mm:ss.SSSSSSSSSXXX');
time_end = string(time_end, 'uuuu-MM-dd''T''HH:mm:ss.SSSSSSSSSXXX');

fields = join(fields, ", ");

sql = sprintf("SELECT ""time"", %s FROM ""%s"" WHERE ""time"" BETWEEN '%s' AND '%s' ORDER BY ""time"" ASC", ...
    fields, ...
    table, ...
    time_start, ...
    time_end ...
    );

data = fetch(connection, sql);
data = table2timetable(data);

end
